name: Lint checks with kondo
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Run Kondo Report
        run: |
          docker run \
              -v $PWD/src:/src \
              --rm cljkondo/clj-kondo \
              clj-kondo --parallel --lint src > report.log
      -name: report
        uses: actions/upload-actifact@v4
        with:
          name: Kondo-Report.txt
          path: report.log
  container:
    if: false
    runs-on: ubuntu-latest
    container:
      image: cljkondo/clj-kondo
      volumes:
        - /__w/guess/guess/src:/src
      options: --cpus 1
    steps:
      - name: show things
        run: pwd ; ls -la
      - name: show root
        run: ls /
      - name: show src
        run: ls /src
      - run: clj-kondo --lint /src
        name: lint from container

