name: Lint checks with kondo
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - run: echo runs directly
        name: Run on VM
  container:
    runs-on: ubuntu-latest
    container:
      image: cljkondo/clj-kondo
      volumes:
        - src:/src
      options: --cpus 1
    steps:
      - run: clj-kondo --lint /src
        name: lint from container

