name: Lint checks with kondo
on:
  push:
    branches: [ main ]
jobs:
  vm:
    steps:
      - run: echo runs directly
        name: Run on VM
  container:
    runs-on: ubuntu-latest
    container:
      image: cljkondo/clj-condo
      volumns:
        - src:/src
    steps:
      - run: clj-kondo --lint src
        name: lint from container

